// Generated by gencpp from file a_halt_action_server/a_haltFeedback.msg
// DO NOT EDIT!


#ifndef A_HALT_ACTION_SERVER_MESSAGE_A_HALTFEEDBACK_H
#define A_HALT_ACTION_SERVER_MESSAGE_A_HALTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace a_halt_action_server
{
template <class ContainerAllocator>
struct a_haltFeedback_
{
  typedef a_haltFeedback_<ContainerAllocator> Type;

  a_haltFeedback_()
    {
    }
  a_haltFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct a_haltFeedback_

typedef ::a_halt_action_server::a_haltFeedback_<std::allocator<void> > a_haltFeedback;

typedef boost::shared_ptr< ::a_halt_action_server::a_haltFeedback > a_haltFeedbackPtr;
typedef boost::shared_ptr< ::a_halt_action_server::a_haltFeedback const> a_haltFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace a_halt_action_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'a_halt_action_server': ['/home/joehuang/Documents/MIT/2.12/team4_arm_ws/devel/share/a_halt_action_server/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::a_halt_action_server::a_haltFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a_halt_action_server/a_haltFeedback";
  }

  static const char* value(const ::a_halt_action_server::a_haltFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
";
  }

  static const char* value(const ::a_halt_action_server::a_haltFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct a_haltFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a_halt_action_server::a_haltFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::a_halt_action_server::a_haltFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // A_HALT_ACTION_SERVER_MESSAGE_A_HALTFEEDBACK_H
