; Auto-generated. Do not edit!


(cl:in-package a_a_action_server-msg)


;//! \htmlinclude a_aFeedback.msg.html

(cl:defclass <a_aFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass a_aFeedback (<a_aFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_aFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_aFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_a_action_server-msg:<a_aFeedback> is deprecated: use a_a_action_server-msg:a_aFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_aFeedback>) ostream)
  "Serializes a message object of type '<a_aFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_aFeedback>) istream)
  "Deserializes a message object of type '<a_aFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_aFeedback>)))
  "Returns string type for a message object of type '<a_aFeedback>"
  "a_a_action_server/a_aFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_aFeedback)))
  "Returns string type for a message object of type 'a_aFeedback"
  "a_a_action_server/a_aFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_aFeedback>)))
  "Returns md5sum for a message object of type '<a_aFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_aFeedback)))
  "Returns md5sum for a message object of type 'a_aFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_aFeedback>)))
  "Returns full string definition for message of type '<a_aFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_aFeedback)))
  "Returns full string definition for message of type 'a_aFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_aFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_aFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'a_aFeedback
))
