; Auto-generated. Do not edit!


(cl:in-package a_a_action_server-msg)


;//! \htmlinclude a_aGoal.msg.html

(cl:defclass <a_aGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass a_aGoal (<a_aGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_aGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_aGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_a_action_server-msg:<a_aGoal> is deprecated: use a_a_action_server-msg:a_aGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_aGoal>) ostream)
  "Serializes a message object of type '<a_aGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_aGoal>) istream)
  "Deserializes a message object of type '<a_aGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_aGoal>)))
  "Returns string type for a message object of type '<a_aGoal>"
  "a_a_action_server/a_aGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_aGoal)))
  "Returns string type for a message object of type 'a_aGoal"
  "a_a_action_server/a_aGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_aGoal>)))
  "Returns md5sum for a message object of type '<a_aGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_aGoal)))
  "Returns md5sum for a message object of type 'a_aGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_aGoal>)))
  "Returns full string definition for message of type '<a_aGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_aGoal)))
  "Returns full string definition for message of type 'a_aGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_aGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_aGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'a_aGoal
))
