; Auto-generated. Do not edit!


(cl:in-package a_a_action_server-msg)


;//! \htmlinclude a_aResult.msg.html

(cl:defclass <a_aResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass a_aResult (<a_aResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_aResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_aResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_a_action_server-msg:<a_aResult> is deprecated: use a_a_action_server-msg:a_aResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_aResult>) ostream)
  "Serializes a message object of type '<a_aResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_aResult>) istream)
  "Deserializes a message object of type '<a_aResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_aResult>)))
  "Returns string type for a message object of type '<a_aResult>"
  "a_a_action_server/a_aResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_aResult)))
  "Returns string type for a message object of type 'a_aResult"
  "a_a_action_server/a_aResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_aResult>)))
  "Returns md5sum for a message object of type '<a_aResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_aResult)))
  "Returns md5sum for a message object of type 'a_aResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_aResult>)))
  "Returns full string definition for message of type '<a_aResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_aResult)))
  "Returns full string definition for message of type 'a_aResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_aResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_aResult>))
  "Converts a ROS message object to a list"
  (cl:list 'a_aResult
))
