// Generated by gencpp from file a_b_action_server/a_bResult.msg
// DO NOT EDIT!


#ifndef A_B_ACTION_SERVER_MESSAGE_A_BRESULT_H
#define A_B_ACTION_SERVER_MESSAGE_A_BRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace a_b_action_server
{
template <class ContainerAllocator>
struct a_bResult_
{
  typedef a_bResult_<ContainerAllocator> Type;

  a_bResult_()
    : succeed(false)  {
    }
  a_bResult_(const ContainerAllocator& _alloc)
    : succeed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeed_type;
  _succeed_type succeed;




  typedef boost::shared_ptr< ::a_b_action_server::a_bResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::a_b_action_server::a_bResult_<ContainerAllocator> const> ConstPtr;

}; // struct a_bResult_

typedef ::a_b_action_server::a_bResult_<std::allocator<void> > a_bResult;

typedef boost::shared_ptr< ::a_b_action_server::a_bResult > a_bResultPtr;
typedef boost::shared_ptr< ::a_b_action_server::a_bResult const> a_bResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::a_b_action_server::a_bResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::a_b_action_server::a_bResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace a_b_action_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'a_b_action_server': ['/home/joehuang/Documents/MIT/2.12/team4_ws/devel/share/a_b_action_server/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::a_b_action_server::a_bResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::a_b_action_server::a_bResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a_b_action_server::a_bResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::a_b_action_server::a_bResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_b_action_server::a_bResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::a_b_action_server::a_bResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::a_b_action_server::a_bResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d9c3b918a0afafe09791ef8d7853918";
  }

  static const char* value(const ::a_b_action_server::a_bResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d9c3b918a0afafeULL;
  static const uint64_t static_value2 = 0x09791ef8d7853918ULL;
};

template<class ContainerAllocator>
struct DataType< ::a_b_action_server::a_bResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a_b_action_server/a_bResult";
  }

  static const char* value(const ::a_b_action_server::a_bResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::a_b_action_server::a_bResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool succeed\n\
";
  }

  static const char* value(const ::a_b_action_server::a_bResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::a_b_action_server::a_bResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct a_bResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::a_b_action_server::a_bResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::a_b_action_server::a_bResult_<ContainerAllocator>& v)
  {
    s << indent << "succeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // A_B_ACTION_SERVER_MESSAGE_A_BRESULT_H
