// Auto-generated. Do not edit!

// (in-package a_b_action_server.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class a_bFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.moved_distance = null;
    }
    else {
      if (initObj.hasOwnProperty('moved_distance')) {
        this.moved_distance = initObj.moved_distance
      }
      else {
        this.moved_distance = new geometry_msgs.msg.Vector3();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type a_bFeedback
    // Serialize message field [moved_distance]
    bufferOffset = geometry_msgs.msg.Vector3.serialize(obj.moved_distance, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type a_bFeedback
    let len;
    let data = new a_bFeedback(null);
    // Deserialize message field [moved_distance]
    data.moved_distance = geometry_msgs.msg.Vector3.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 24;
  }

  static datatype() {
    // Returns string type for a message object
    return 'a_b_action_server/a_bFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f4cbd35290f8c2d64781aec16f1ffd5e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/Vector3 moved_distance
    
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new a_bFeedback(null);
    if (msg.moved_distance !== undefined) {
      resolved.moved_distance = geometry_msgs.msg.Vector3.Resolve(msg.moved_distance)
    }
    else {
      resolved.moved_distance = new geometry_msgs.msg.Vector3()
    }

    return resolved;
    }
};

module.exports = a_bFeedback;
