; Auto-generated. Do not edit!


(cl:in-package a_b_action_server-msg)


;//! \htmlinclude a_bFeedback.msg.html

(cl:defclass <a_bFeedback> (roslisp-msg-protocol:ros-message)
  ((moved_distance
    :reader moved_distance
    :initarg :moved_distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass a_bFeedback (<a_bFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_bFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_bFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_b_action_server-msg:<a_bFeedback> is deprecated: use a_b_action_server-msg:a_bFeedback instead.")))

(cl:ensure-generic-function 'moved_distance-val :lambda-list '(m))
(cl:defmethod moved_distance-val ((m <a_bFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader a_b_action_server-msg:moved_distance-val is deprecated.  Use a_b_action_server-msg:moved_distance instead.")
  (moved_distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_bFeedback>) ostream)
  "Serializes a message object of type '<a_bFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'moved_distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_bFeedback>) istream)
  "Deserializes a message object of type '<a_bFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'moved_distance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_bFeedback>)))
  "Returns string type for a message object of type '<a_bFeedback>"
  "a_b_action_server/a_bFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_bFeedback)))
  "Returns string type for a message object of type 'a_bFeedback"
  "a_b_action_server/a_bFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_bFeedback>)))
  "Returns md5sum for a message object of type '<a_bFeedback>"
  "7b76df385ed63be519f1a18aa757604d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_bFeedback)))
  "Returns md5sum for a message object of type 'a_bFeedback"
  "7b76df385ed63be519f1a18aa757604d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_bFeedback>)))
  "Returns full string definition for message of type '<a_bFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 moved_distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_bFeedback)))
  "Returns full string definition for message of type 'a_bFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 moved_distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_bFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_bFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'a_bFeedback
    (cl:cons ':moved_distance (moved_distance msg))
))
