; Auto-generated. Do not edit!


(cl:in-package a_b_action_server-msg)


;//! \htmlinclude a_bGoal.msg.html

(cl:defclass <a_bGoal> (roslisp-msg-protocol:ros-message)
  ((force
    :reader force
    :initarg :force
    :type cl:float
    :initform 0.0)
   (goal_distance
    :reader goal_distance
    :initarg :goal_distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass a_bGoal (<a_bGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_bGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_bGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_b_action_server-msg:<a_bGoal> is deprecated: use a_b_action_server-msg:a_bGoal instead.")))

(cl:ensure-generic-function 'force-val :lambda-list '(m))
(cl:defmethod force-val ((m <a_bGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader a_b_action_server-msg:force-val is deprecated.  Use a_b_action_server-msg:force instead.")
  (force m))

(cl:ensure-generic-function 'goal_distance-val :lambda-list '(m))
(cl:defmethod goal_distance-val ((m <a_bGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader a_b_action_server-msg:goal_distance-val is deprecated.  Use a_b_action_server-msg:goal_distance instead.")
  (goal_distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_bGoal>) ostream)
  "Serializes a message object of type '<a_bGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'force))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'goal_distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_bGoal>) istream)
  "Deserializes a message object of type '<a_bGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'force) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'goal_distance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_bGoal>)))
  "Returns string type for a message object of type '<a_bGoal>"
  "a_b_action_server/a_bGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_bGoal)))
  "Returns string type for a message object of type 'a_bGoal"
  "a_b_action_server/a_bGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_bGoal>)))
  "Returns md5sum for a message object of type '<a_bGoal>"
  "051f5410092db6d015c1933bfc45c200")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_bGoal)))
  "Returns md5sum for a message object of type 'a_bGoal"
  "051f5410092db6d015c1933bfc45c200")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_bGoal>)))
  "Returns full string definition for message of type '<a_bGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 force~%float32 goal_distance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_bGoal)))
  "Returns full string definition for message of type 'a_bGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 force~%float32 goal_distance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_bGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_bGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'a_bGoal
    (cl:cons ':force (force msg))
    (cl:cons ':goal_distance (goal_distance msg))
))
