; Auto-generated. Do not edit!


(cl:in-package a_b_action_server-msg)


;//! \htmlinclude a_bResult.msg.html

(cl:defclass <a_bResult> (roslisp-msg-protocol:ros-message)
  ((succeed
    :reader succeed
    :initarg :succeed
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass a_bResult (<a_bResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_bResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_bResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_b_action_server-msg:<a_bResult> is deprecated: use a_b_action_server-msg:a_bResult instead.")))

(cl:ensure-generic-function 'succeed-val :lambda-list '(m))
(cl:defmethod succeed-val ((m <a_bResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader a_b_action_server-msg:succeed-val is deprecated.  Use a_b_action_server-msg:succeed instead.")
  (succeed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_bResult>) ostream)
  "Serializes a message object of type '<a_bResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'succeed) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_bResult>) istream)
  "Deserializes a message object of type '<a_bResult>"
    (cl:setf (cl:slot-value msg 'succeed) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_bResult>)))
  "Returns string type for a message object of type '<a_bResult>"
  "a_b_action_server/a_bResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_bResult)))
  "Returns string type for a message object of type 'a_bResult"
  "a_b_action_server/a_bResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_bResult>)))
  "Returns md5sum for a message object of type '<a_bResult>"
  "8d9c3b918a0afafe09791ef8d7853918")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_bResult)))
  "Returns md5sum for a message object of type 'a_bResult"
  "8d9c3b918a0afafe09791ef8d7853918")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_bResult>)))
  "Returns full string definition for message of type '<a_bResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool succeed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_bResult)))
  "Returns full string definition for message of type 'a_bResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool succeed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_bResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_bResult>))
  "Converts a ROS message object to a list"
  (cl:list 'a_bResult
    (cl:cons ':succeed (succeed msg))
))
