; Auto-generated. Do not edit!


(cl:in-package a_b_action_server-msg)


;//! \htmlinclude a_bResult.msg.html

(cl:defclass <a_bResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass a_bResult (<a_bResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_bResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_bResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_b_action_server-msg:<a_bResult> is deprecated: use a_b_action_server-msg:a_bResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_bResult>) ostream)
  "Serializes a message object of type '<a_bResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_bResult>) istream)
  "Deserializes a message object of type '<a_bResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_bResult>)))
  "Returns string type for a message object of type '<a_bResult>"
  "a_b_action_server/a_bResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_bResult)))
  "Returns string type for a message object of type 'a_bResult"
  "a_b_action_server/a_bResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_bResult>)))
  "Returns md5sum for a message object of type '<a_bResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_bResult)))
  "Returns md5sum for a message object of type 'a_bResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_bResult>)))
  "Returns full string definition for message of type '<a_bResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_bResult)))
  "Returns full string definition for message of type 'a_bResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_bResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_bResult>))
  "Converts a ROS message object to a list"
  (cl:list 'a_bResult
))
