(cl:defpackage a_halt_action_server-msg
  (:use )
  (:export
   "<A_HALTACTION>"
   "A_HALTACTION"
   "<A_HALTACTIONFEEDBACK>"
   "A_HALTACTIONFEEDBACK"
   "<A_HALTACTIONGOAL>"
   "A_HALTACTIONGOAL"
   "<A_HALTACTIONRESULT>"
   "A_HALTACTIONRESULT"
   "<A_HALTFEEDBACK>"
   "A_HALTFEEDBACK"
   "<A_HALTGOAL>"
   "A_HALTGOAL"
   "<A_HALTRESULT>"
   "A_HALTRESULT"
  ))

