; Auto-generated. Do not edit!


(cl:in-package a_halt_action_server-msg)


;//! \htmlinclude a_haltResult.msg.html

(cl:defclass <a_haltResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass a_haltResult (<a_haltResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_haltResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_haltResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_halt_action_server-msg:<a_haltResult> is deprecated: use a_halt_action_server-msg:a_haltResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_haltResult>) ostream)
  "Serializes a message object of type '<a_haltResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_haltResult>) istream)
  "Deserializes a message object of type '<a_haltResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_haltResult>)))
  "Returns string type for a message object of type '<a_haltResult>"
  "a_halt_action_server/a_haltResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_haltResult)))
  "Returns string type for a message object of type 'a_haltResult"
  "a_halt_action_server/a_haltResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_haltResult>)))
  "Returns md5sum for a message object of type '<a_haltResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_haltResult)))
  "Returns md5sum for a message object of type 'a_haltResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_haltResult>)))
  "Returns full string definition for message of type '<a_haltResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_haltResult)))
  "Returns full string definition for message of type 'a_haltResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_haltResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_haltResult>))
  "Converts a ROS message object to a list"
  (cl:list 'a_haltResult
))
