; Auto-generated. Do not edit!


(cl:in-package a_halt_action_server-msg)


;//! \htmlinclude a_haltGoal.msg.html

(cl:defclass <a_haltGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass a_haltGoal (<a_haltGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_haltGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_haltGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_halt_action_server-msg:<a_haltGoal> is deprecated: use a_halt_action_server-msg:a_haltGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_haltGoal>) ostream)
  "Serializes a message object of type '<a_haltGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_haltGoal>) istream)
  "Deserializes a message object of type '<a_haltGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_haltGoal>)))
  "Returns string type for a message object of type '<a_haltGoal>"
  "a_halt_action_server/a_haltGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_haltGoal)))
  "Returns string type for a message object of type 'a_haltGoal"
  "a_halt_action_server/a_haltGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_haltGoal>)))
  "Returns md5sum for a message object of type '<a_haltGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_haltGoal)))
  "Returns md5sum for a message object of type 'a_haltGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_haltGoal>)))
  "Returns full string definition for message of type '<a_haltGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_haltGoal)))
  "Returns full string definition for message of type 'a_haltGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_haltGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_haltGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'a_haltGoal
))
