; Auto-generated. Do not edit!


(cl:in-package a_halt_action_server-msg)


;//! \htmlinclude a_haltFeedback.msg.html

(cl:defclass <a_haltFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass a_haltFeedback (<a_haltFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <a_haltFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'a_haltFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name a_halt_action_server-msg:<a_haltFeedback> is deprecated: use a_halt_action_server-msg:a_haltFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <a_haltFeedback>) ostream)
  "Serializes a message object of type '<a_haltFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <a_haltFeedback>) istream)
  "Deserializes a message object of type '<a_haltFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<a_haltFeedback>)))
  "Returns string type for a message object of type '<a_haltFeedback>"
  "a_halt_action_server/a_haltFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'a_haltFeedback)))
  "Returns string type for a message object of type 'a_haltFeedback"
  "a_halt_action_server/a_haltFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<a_haltFeedback>)))
  "Returns md5sum for a message object of type '<a_haltFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'a_haltFeedback)))
  "Returns md5sum for a message object of type 'a_haltFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<a_haltFeedback>)))
  "Returns full string definition for message of type '<a_haltFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'a_haltFeedback)))
  "Returns full string definition for message of type 'a_haltFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <a_haltFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <a_haltFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'a_haltFeedback
))
